project_id = "sentinel-derm"

[api]
enabled = true
port = 55431
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 55432
shadow_port = 55430
major_version = 15

[studio]
enabled = true
port = 55433
api_url = "http://127.0.0.1:55431"

[inbucket]
enabled = true
port = 55434
smtp_port = 55435
pop3_port = 55436

[storage]
enabled = true
file_size_limit = "100MiB"

[analytics]
enabled = true
port = 55437

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = true

[functions.process-patient-image]
verify_jwt = true
